### ISSUE TITLE
Order of the columns is different from the Mapping classes

### ISSUE THREAD

**Issue by chaks7** [JSqlServerBulkInsert/JSqlServerBulkInsert#17]
I am using this JAR in a project at my work place. It performs pretty good. Thank you for making the code open source.

I ran into an issue where the Mapping classes are generated and the order may not be same as the order of the columns in the SQL Server. Is this a limitation in the library or did I overlook something?

-chaks7

**Comment by bytefish** [comment]
Could you make up a small example and show where it fails? This would be great as a starting point. I have hoped for by mapping by column name, that the order doesn’t matter. Apparently it does.

**Comment by bytefish** [comment]
I think the problem is related to setting the ordinals of the table columns here:

https://github.com/JSqlServerBulkInsert/JSqlServerBulkInsert/blob/master/JSqlServerBulkInsert/src/main/java/de/bytefish/jsqlserverbulkinsert/records/SqlServerBulkData.java#L48

This probably leads to wrong mappings, when not all columns are set.

**Comment by bytefish** [comment]
Looking up the Microsoft implementation, they require all columns to be set:

* https://github.com/microsoft/mssql-jdbc/blob/561d10862a5f647d281145ceb131ef6ecbeeedff/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java#L2143

**Comment by bytefish** [comment]
@chaks7 I have researched the Microsoft Implementations for the Batch inserts. They always require to match the Actual Schema and the Data 1-1. This is because  deep down I need to provide the Data to be written as an Object[] with no additional information about the associated columns:

* https://github.com/JSqlServerBulkInsert/JSqlServerBulkInsert/blob/master/JSqlServerBulkInsert/src/main/java/de/bytefish/jsqlserverbulkinsert/records/SqlServerBulkData.java#L81

When the Microsoft SqlBulkCopy implementation asks for the Ordinals, then a ``Set<int>`` is returned, which has no order at all:

* https://github.com/JSqlServerBulkInsert/JSqlServerBulkInsert/blob/master/JSqlServerBulkInsert/src/main/java/de/bytefish/jsqlserverbulkinsert/records/SqlServerBulkData.java#L56

Maybe it is possible to fill the Object Array with Nulls and hope Microsofts implementations are not calling them, but this is based on many assumptions.

**Comment by bytefish** [comment]
I have added a Pull Request to validate the mappings and sort them, if it is a valid mapping:

* https://github.com/JSqlServerBulkInsert/JSqlServerBulkInsert/pull/18

Still all columns have to be mapped.

**Comment by chaks7** [comment]
Did not expect such a fast turn-around. Will take a look at the code, thank you for looking into it.

Was using this work around.

`   public void saveAll(Connection connection, SQLServerBulkCopyOptions options, Stream<TEntity> entities) {
        // Create a new SQLServerBulkCopy Instance on the given Connection:
        try (SQLServerBulkCopy sqlServerBulkCopy = new SQLServerBulkCopy(connection)) {
        	
        	
            // Set the Options:
            sqlServerBulkCopy.setBulkCopyOptions(options);
            // The Destination Table to write to:
            sqlServerBulkCopy.setDestinationTableName(mapping.getTableDefinition().GetFullQualifiedTableName());
            
            List<IColumnDefinition<TEntity>> sortedList = buildColumnMapping(connection);
            
            // The SQL Records to insert:
            ISQLServerBulkData record = new SqlServerBulkData<TEntity>(sortedList, entities.iterator());
            // Finally start the Bulk Copy Process:
            sqlServerBulkCopy.writeToServer(record);
            // Handle Exceptions:
        } catch (SQLServerException e) {
            // Wrap it in a RunTimeException to provide a nice API:
            throw new RuntimeException(e);
        } catch (SQLException e) {
			// Wrap it in a RunTimeException to provide a nice API:
        	throw new RuntimeException(e);
		}
    }

    private List<IColumnDefinition<TEntity>> buildColumnMapping(Connection connection) throws SQLException {
    	
    	DatabaseMetaData databaseMetaData = connection.getMetaData();
    	
    	ResultSet columns = databaseMetaData.getColumns(null,null, mapping.getTableDefinition().getTableName(), null);
    	
    	List<String> columnList = new ArrayList<>();
    	
    	while(columns.next()) {
    		 String columnName = columns.getString("COLUMN_NAME");
    		 columnList.add(columnName);
    	}
    	
    	List<IColumnDefinition<TEntity>> sortedList = new ArrayList<>();
    	
    	for(String columnName : columnList)
    	{
    		IColumnDefinition<TEntity> found = mapping.getColumns()
    									.stream()
								    	.filter(m -> m.getColumnMetaData().getName().equalsIgnoreCase(columnName))
								    	.findFirst()
								    	.orElse(null);
    		
    		if(found != null)
    		{
    			sortedList.add(found);
    		}
    	}
    	
    	return sortedList;
	}
`

**Comment by bytefish** [comment]
Uh maybe what I did is overly complicated. Does the MetaData also contain the Ordinal Value? If so one can dump all Information Schema stuff I did to get the metadata. 😳😬

**Comment by chaks7** [comment]
No, it does not have the Ordinal Value.

`public ColumnMetaData(String name, int type, int precision, int scale, boolean isAutoIncrement) {
        this.name = name;
        this.type = type;
        this.precision = precision;
        this.scale = scale;
        this.isAutoIncrement = isAutoIncrement;
    }`

**Comment by bytefish** [comment]
Yes. I was asking for the JDBC ``connection.getMetaData();`` call and it does indeed contain the Ordinal Value. Should have read the Java documentation first. So I could remove all my queries to the SQL Server "Information Schema", because all required meta data is already built into the JDBC driver. This simplifies the code.

**Comment by chaks7** [comment]
Yes, got it.

**Comment by bytefish** [comment]
I will wait for @vslee to look into it, before releasing it. 👍

**Comment by bytefish** [comment]
@chaks7 I have released it to Maven as 4.0.0. It will be available once Maven syncs, which can take up to some hours. Please give it a try and let me know if it fixes the problem!

**Comment by chaks7** [comment]
@bytefish It works. I downloaded it from Maven.

My only wish is, if we can optimize the call to get the Columns/Ordinal once and not call it on every save. I wish Java supported something similar to Lazy<T> in .Net. If we can lazily initialize the field, it will reduce the over-head. In my code path, we save the DTOs every 5000 records. When we are doing this for a few 10 of millions records, those milli-seconds add up. Still it is not bad.

I see some suggestions how to do that in this stackoverflow thread: https://stackoverflow.com/questions/29132884/lazy-field-initialization-with-lambdas

Will give it a try and let you know how it goes in the coming week.

PS: Can't thank you, @bytefish and @vslee enough for this project and the work you have put so far. Sincere regards and much appreciation.

**Comment by bytefish** [comment]
Totally reasonable! 👍  It makes absolutely no sense, to query the Metadata more than once. I have modified the implementation, so the query to the database is only executed on first call to the save method. I have released it to Maven as 4.0.1, which should be available some time soon.

**Comment by bytefish** [comment]
@vslee I am very sorry, because I destroyed the v3.0.0 release notes when draftig the new release. I wanted to rename the Version Numbers from "v3.0.0" to "3.0.0" and accidentally created new tags. When I wanted to remove the Tag, I accidentally deleted the Drafted Release. Any idea, if this can be repaired?

**Comment by vslee** [comment]
I think I fixed it. The reason I started prefixing the versions with 'v' is bc GitHub suggests it in the new release page:
![image](https://user-images.githubusercontent.com/366757/107886558-9ba66f80-6ea4-11eb-8e92-0ae2d6b902b4.png)
Looks like that might just be a old carryover from semver v1 though: https://stackoverflow.com/questions/2006265/is-there-a-standard-naming-convention-for-git-tags

**Comment by bytefish** [comment]
Ah, OK. We can also rename it as v<Version Number>. I have no preferences.

**Comment by vslee** [comment]
Me neither. I think since you just converted it to non 'v', and the 'v' is just a historical holdover, we can just keep it as is for now unless starts causing people issues.

**Comment by bytefish** [comment]
@chaks7 @vslee To share some knowledge on alternative ways. I found the ``SqlServerBulkCopy`` quite limiting. If you are only doing Inserts, then everything is good. But what if you need to update data also? One could of course use Staging Tables etc., but I found Table-valued Parameters a way better approach for complex scenarios.

I made an example for a Java implementation here:

* https://github.com/bytefish/SqlServerTvpExample

This way you can use a ``MERGE`` Statement in a Stored Procedure for Insert / Update and still pass Batches of data into the Stored Procedure. The upside is: This approach contains absolutely no magic and one doesn't need to rely on projects like this, which also helps to stay up to date with the driver.

I have used this pattern to great success in many projects.

**Comment by vslee** [comment]
Looks like TVP is a better way to go. Probably would have to be a long term goal though, since it would involve rewriting pretty much this entire library.

**Comment by bytefish** [comment]
I see this library as a simplified way to quickly bulk insert data into a table without the hassle of writing and maintaining stored procedures. But the thing is, that often some additional things need to be done during the Bulk Insert, like updating existing rows and so on. And this where I would use the TVP approach.

**Comment by vslee** [comment]
Theoretically, the library could one day create the stored procedure automatically prior to use, and then clean it up afterwards.

**Comment by chaks7** [comment]
> I see this library as a simplified way to quickly bulk insert data into a table without the hassle of writing and maintaining stored procedures. But the thing is, that often some additional things need to be done during the Bulk Insert, like updating existing rows and so on. And this where I would use the TVP approach.

This is the exact use-case for me. We have hierarchical database and we need to migrate those records/data to SQL Server. So we are doing INSERTs. I looked at TVP, but it requires lot more work, setting up staging table and stored proc, and we have more than 200 tables. JDBC Batching was also considered, but it is a bunch of insert statements, and it is not as performant as BULK INSERTs.
