### ISSUE TITLE
Problem when bulk inserting java LocalDateTime to mssql datetime2 in database

### ISSUE THREAD

**Issue by synchas** [JSqlServerBulkInsert/JSqlServerBulkInsert#20]
When parsing a file containing a LocalDateTime with format "dd/MM/yyyy h:mm:ss aZ", the value inserted in the database is the value from the file minus 1 hour (see image).

![image](https://user-images.githubusercontent.com/111984861/195613711-e0e55a9a-3fa4-4160-8a18-cd4c4def5bb1.png)

**Comment by bytefish** [comment]
Do you see if there is any problem in this test:

* https://github.com/JSqlServerBulkInsert/JSqlServerBulkInsert/blob/master/JSqlServerBulkInsert/src/test/java/de/bytefish/jsqlserverbulkinsert/test/mapping/LocalDateTimeTest.java

This deals with reading and writing a LocalDateTime to SQL Server.

**Comment by bytefish** [comment]
Please reopen, if the problem persists and the LocalDateTime test has issues.
