### ISSUE TITLE
Please exclude computed columns before adding the column to List<SchemaMetaData.ColumnInformation>

### ISSUE THREAD

**Issue by chaks7** [JSqlServerBulkInsert/JSqlServerBulkInsert#22]
https://github.com/JSqlServerBulkInsert/JSqlServerBulkInsert/blob/724255afac2be02331ca1a66ca67aa295c21dc52/JSqlServerBulkInsert/src/main/java/de/bytefish/jsqlserverbulkinsert/util/SchemaUtils.java#L26

When adding the columns to the collection, can we check if the column is computed column or not?

We recently added computed columns (4 columns), and that is breaking the Column Mapping. Below is the error message:
java.lang.RuntimeException: Destination Table has '72' columns, the Source Mapping has '68' columns.
        at de.bytefish.jsqlserverbulkinsert.util.SchemaUtils.validateColumnMapping(SchemaUtils.java:65) ~[jsqlserverbulkinsert-4.0.1.jar:?]
        at de.bytefish.jsqlserverbulkinsert.SqlServerBulkInsert.validateAndInitializeWithMetaData(SqlServerBulkInsert.java:68) ~[jsqlserverbulkinsert-4.0.1.jar:?]
        at de.bytefish.jsqlserverbulkinsert.SqlServerBulkInsert.saveAll(SqlServerBulkInsert.java:36) ~[jsqlserverbulkinsert-4.0.1.jar:?]

while (rs.next())
			{
				if(rs.getString("IS_GENERATEDCOLUMN").equals("NO"))
				{
					SchemaMetaData.ColumnInformation columnInformation = new SchemaMetaData.ColumnInformation(
							rs.getString("COLUMN_NAME"),
							rs.getInt("ORDINAL_POSITION")

					);
					columnInformations.add(columnInformation);
				}
			}

**Comment by bytefish** [comment]
Sure, a PR is appreciated. 👍

**Comment by bytefish** [comment]
@chaks7 A minimal example to use for a unit test would be great, so I could add it to the tests.

**Comment by chaks7** [comment]
@bytefish Looked into the issue more. Problem is at 2 places. SchemaUtils class which reads both non-computed columns and computed columns that are not persisted and the Microsoft MSSQL JDBC driver. Before doing the BULK INSERT, the JDBC driver reads the schema to get the column metadata and does not filter computed columns: https://github.com/microsoft/mssql-jdbc/blob/eae6d7b33571c92029169b33378b2405e8df448a/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java#L1737

Before fixing the problem in this library, Microsoft needs to address the problem in the JDBC driver.
We may have to change the table definition before importing the data, and apply the computed columns after inserting the data as a work-around.

**Comment by bytefish** [comment]
@chaks7 I think it should be possible. Having computed columns in a Table definition is such an obvious use case, I would be surprised if it’s not possible. They also seem to account for computed columns in the JDBC driver:

https://github.com/microsoft/mssql-jdbc/blob/eae6d7b33571c92029169b33378b2405e8df448a/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java#L1756

I will take a look at it, when I have a working development machine at my hands.

**Comment by bytefish** [comment]
It also looks like a bug with Computed Columns has been fixed lately:

* https://learn.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver16#fixes-in-126

Anyways I am afraid, that I can't get my old GPG Keys to sign releases to Central Maven repositories... Out of the blue I would say, I could just generate a new keypair as packages as packages there only need to contain a valid signature. 🤷‍♂️

**Comment by chaks7** [comment]
@bytefish Indeed, the issue has been resolved in the 12.6 release. Was using an older version. We need to incorporate the filter to exclude computed columns (whether persisted or not) in the library. I can confirm that it works with that change.

**Comment by chaks7** [comment]
@bytefish PR is available now. Please feel free to modify, thank you for your time.

**Comment by bytefish** [comment]
@chaks7 Great job! You understood this libraries code faster, than I did. 🫣 I will take a look at the PR and try to release to Maven Central as soon as possible.

**Comment by bytefish** [comment]
@vslee @chaks7 I am not so much into Java at the moment, and I am unsure, so maybe you can help me. I know the Maven file targeted a specific Java version:

https://github.com/JSqlServerBulkInsert/JSqlServerBulkInsert/blob/b4b895b68f7668104d5e2048c85bc46b38549d1a/JSqlServerBulkInsert/pom.xml#L52

In .NET world the Target Runtime was (and sometimes still is) a huge drama for my libraries, because of people still running older (but still supported by Microsoft) runtimes. 

What is the most appropriate version to set this to? Are people still running 1.8? Do I need to build the package with same Java SDK targeted in the POM? Why is Microsoft releasing their packages with a “.jre11” suffix?

**Comment by chaks7** [comment]
Looks like you can target multiple JREs.
https://github.com/microsoft/mssql-jdbc/blob/eae6d7b33571c92029169b33378b2405e8df448a/pom.xml#L283
https://github.com/microsoft/mssql-jdbc/blob/eae6d7b33571c92029169b33378b2405e8df448a/pom.xml#L316C4-L316C18

**Comment by bytefish** [comment]
@chaks7 Do you happen to know, if I need to have the specific runtimes installed for the generated Bytecode compatibility? Also @vslee  would it be preferable to release with jre11 and so on suffixes? Would one also need to reference the specific SQL Server JDBC driver with a jre21 suffix for example? 🫣

**Comment by vslee** [comment]
> would it be preferable to release with jre11 and so on suffixes? Would one also need to reference the specific SQL Server JDBC driver with a jre21 suffix for example? 🫣

Not sure. I mostly do dotnet stuff. In dotnet, when the library is on an old version, it can usually be used by newer versions without issue.

**Comment by vslee** [comment]
Looks like for the current version, it references the jre8 version but allows ppl to use the jre11 version as an update. So if you reference the jre8 version of 12.6, it should allow users to use the jre11 version without you having to add anything.

![image](https://github.com/JSqlServerBulkInsert/JSqlServerBulkInsert/assets/366757/8888b04e-b178-4772-b0eb-56576e945bfd)

**Comment by bytefish** [comment]
@chaks7 @vslee Wow, releasing this from China was quite an adventure. Once I am back it's probably useful to add GitHub Actions to all my projects, instead of using a... Batch script. Like every security-minded person I had my Signing Keys  accidentally backed up in OneDrive (of course). 👌

A `5.1.0` should be in Maven once it synchronizes, please let me know, if it works as expected.
